// <auto-generated />
using FUSCA_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FUSCA_API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230619115516_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FUSCA_API.Models.Entrega", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Dt_Entrega")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hr_Entrega")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Local_Entrega")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo_Entrega")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Entregas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Dt_Entrega = "01/05/1760",
                            Hr_Entrega = "10:10",
                            Local_Entrega = "Rua São João",
                            Tipo_Entrega = "Sedex"
                        },
                        new
                        {
                            Id = 2,
                            Dt_Entrega = "02/05/1760",
                            Hr_Entrega = "11:11",
                            Local_Entrega = "Rua Santo Antônio",
                            Tipo_Entrega = "ONG"
                        },
                        new
                        {
                            Id = 3,
                            Dt_Entrega = "03/05/1760",
                            Hr_Entrega = "22:22",
                            Local_Entrega = "Rua Santa Maria",
                            Tipo_Entrega = "Sedex"
                        },
                        new
                        {
                            Id = 4,
                            Dt_Entrega = "04/05/1760",
                            Hr_Entrega = "09:09",
                            Local_Entrega = "Rua Josino",
                            Tipo_Entrega = "ONG"
                        },
                        new
                        {
                            Id = 5,
                            Dt_Entrega = "05/05/1760",
                            Hr_Entrega = "08:08",
                            Local_Entrega = "Rua do Vieira",
                            Tipo_Entrega = "Retirada"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
